### ISSUE TITLE
Spin up docs

### ISSUE THREAD

**Issue by pirog** [lando/platformsh#130]
still a bit TBD on this one but we should have a basic docs site for the plugin even if its not hosted

**Comment by labboy0276** [comment]
@pirog It looks like they converted the default aloglia stuff to this docsearch algolia search: https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#install  which seems a little different, you can tell by the new docs search as well.  

I think we need to apply here: https://docsearch.algolia.com/.  I can keep trying, but the plugin doesn't work with our old algolia creds it seems.
