### ISSUE TITLE
Using pull to get database fails with duplicate key error

### ISSUE THREAD

**Issue by hades200082** [lando/platformsh#143]
I get the error `ERROR 1062 (23000) at line 2424: Duplicate entry '759162-??-0' for key 'PRIMARY'` when running `lando pull` and selecting only the database to be pulled.

**Comment by reynoldsalec** [comment]
@hades200082 this is likely an issue with your database, see https://stackoverflow.com/questions/25483798/error-1062-23000-duplicate-entry-for-key-primary for a couple ideas on how to address.
