### ISSUE TITLE
Doesn't seem to work properly on Apple Silicon

### ISSUE THREAD

**Issue by xtfer** [lando/platformsh#150]
Doesn't start up properly, attempts to use amd64 containers, wont run deploy or build hooks.

**Comment by reynoldsalec** [comment]
@xtfer if you could please provide your Landofile and any other details; I'm running an M1 Mac and am able to run a fairly wide swathe of P.sh-powered recipes, so might be able to help replicate your issue and narrow it down.

**Comment by xtfer** [comment]
Sorry @reynoldsalec, I should have closed this. I think it was https://github.com/lando/lando/issues/3329, which has been closed.

**Comment by reynoldsalec** [comment]
NP, thanks for closing the loop @xtfer!
