### ISSUE TITLE
Redis extension unknown with platform.sh recipe and PHP 8.1

### ISSUE THREAD

**Issue by aimfeld** [lando/platformsh#165]
After changing the php version from 8.0 to 8.1 in .platform.app.yaml, I get the following error after lando destroy and lando rebuild: Exception: Extension '{'configuration': {}, 'name': u'redis'}' is unknown 

We had this exact same problem when upgrading from PHP 7.4 to 8.0: https://github.com/lando/platformsh/issues/31
After some back and forth, @pirog and @trolologuy were able to replicate and fix the problem for PHP 8.0. Could you have a look and try to make redis work for 8.1 as well?

Platform.sh supports the redis and igbinary module for PHP 8.1, see https://docs.platform.sh/languages/php/extensions.html

**Comment by mikeshiyan** [comment]
I also get this error. So it wasn't fixed. I'll try the mentioned workaround, thanks to @aimfeld

**Comment by khaldoonmasud** [comment]
I was getting the same error when I was trying to upgrade from php 7.4 to 8.1.
I used the suggested [hack](https://github.com/lando/platformsh/issues/165#issuecomment-1152494241) to fix the issue. Thanks 

```
services:
  app-service:
    overrides:
      image: docker.registry.platform.sh/php-8.1:stable
```
