### ISSUE TITLE
Fixing DB port with portforward is not working

### ISSUE THREAD

**Issue by aimfeld** [lando/platformsh#39]
I'm trying to set a fixed port for the DB connection according to the [guide](https://docs.lando.dev/guides/external-access.html#locking-down-ports). However, the port keeps getting assigned randomly on every `lando rebuild` and `lando restart`, as shown by `lando info`. Maybe this doesn't work with the `platformsh` recipe?

I have this in my .lando.yaml (I tried other port numbers, no luck):
```
services:
  database:
    portforward: 3307
```

**Comment by markushausammann** [comment]
I have this problem in 3.6.5

**Comment by jasloe** [comment]
I, too, have this problem in 3.6.5. 

`lando rebuild` with the following configuration: 

```
services:
  db:
    portforward: 3333
  db2:
    portforward: 4444
```
yields:
```
{ service: 'db',
...
  external_connection: { host: '127.0.0.1', port: '58789' },
...
```
and
```
{ service: 'db',
...
  external_connection: { host: '127.0.0.1', port: '58787' },
...
```

Checking the ports shows:
```
lsof -i:3333
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 54451 jasloe   85u  IPv4 0x81f000c092148157      0t0  TCP localhost:dec-notes (LISTEN)

lsof -i:4444
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 54451 jasloe   78u  IPv4 0x81f000c05f7b8adf      0t0  TCP localhost:krb524 (LISTEN)
```

So, no idea what's going on here.

**Comment by amaisano** [comment]
Same issue on `v3.18.0`. Cannot set my database portforward to `3307`. Use to work in the old days :(
