### ISSUE TITLE
Problems starting Platform.sh recipe: "fatal: unable to lock supervise/lock: temporary failure"

### ISSUE THREAD

**Issue by jasonevines** [lando/platformsh#53]
**Tell us about your setup**

v.3.1.2 on Mac OS X Big Sur

**Tell us about your `.lando.yml`**

(Files renamed not to be hidden and to use .txt extension so I can upload them to GitHub)

[.lando.yml](https://github.com/lando/lando/files/6351565/lando.txt)
.[lando.upstream.yml](https://github.com/lando/lando/files/6351745/lando.upstream.txt)
[.platform.app.yaml](https://github.com/lando/lando/files/6351566/platform.app.txt)

(Files renamed to use .txt extension so I can upload them to GitHub)

[.platform/services.yaml](https://github.com/lando/lando/files/6351589/services.txt)
[.platform/routes.yaml](https://github.com/lando/lando/files/6351596/routes.txt)

**Tell us about the command you were running**

```bash
lando init --source cwd --recipe platformsh
lando start -vvv
```

**Tell us about the error you got**

Logs from the "db" service:

[lando-logs-db-service.txt](https://github.com/lando/lando/files/6351646/lando-logs-db-service.txt)

Logs from the "app" service:

[lando-logs-app-service.txt](https://github.com/lando/lando/files/6351652/lando-logs-app-service.txt)

**Tell us generally about your bug**

I'm trying to boot up the Lando Platform.sh recipe from an existing Drupal 8 Composer codebase. I ran "lando init --source platformsh" in another folder, copied the Platform.sh config files and the Lando config files to the existing project, and then modified as demonstrated in the attachments.

Judging only from the output on the command line, everything appears to go fine; no errors are reported. And all package installations and compilations appear to finish successfully.

But in the logs for every service using Platform.sh images, lines like "runsv app: fatal: unable to lock supervise/lock: temporary failure" repeat a bunch of times. And in the logs for the app service, this error appears: "ERROR Unable to render template /etc/nginx/nginx.conf".

The practical effect is that relationships like the database are inaccessible, so the Lando app is unusable.

**Comment by reynoldsalec** [comment]
I believe the root issue here is Mariadb:10.5, which has been a longstanding issue on Lando: #63 

Closing as a dup, since progress has continued on that ticket.
